# Framework for running automated tests on Open Source Brain using Travis-CI.
# See https://github.com/OpenSourceBrain/osb-model-validation for more details

dist: xenial
sudo: false

services:
  # to prevent error with gui elements
  - xvfb 

addons:
  apt:
    packages:
       # Requirements for Neuron/OMV/etc
    - python-numpy 
    - python-scipy 
    - python-tornado
    - python-matplotlib 
    - python-tk
    - python-dev

language: python
python:
     - "2.7"
     - "3.6"


env:
     - OMV_ENGINE=jNeuroML
     - OMV_ENGINE=NON_OMV_TESTS
     

#before_install:
    # To run tests requiring a graphical user interface on Travis CI, use xvfb (X Virtual Framebuffer) to imitate a display.
    #- "export DISPLAY=:99.0"
    #- "sh -e /etc/init.d/xvfb start"

install:
    # Required to run OMV tests
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    
    # Install specific version of PyOpenWorm
    - git clone https://github.com/openworm/PyOpenWorm.git
    - cd PyOpenWorm
    - git checkout ow-0.9
    - pip install pyparsing==2.0.3 Jinja2==2.11.1 configparser==4.0.2 GitPython==2.1.11 gitdb2==2.0.6 numpydoc==0.9.2
    - python setup.py install
    - pow clone https://github.com/openworm/OpenWormData.git
    - cd examples
    - python NetworkInfo.py # test example...
    - cd ../..
    
    # NeuroML & main install
    - pip install pyNeuroML
    - python setup.py install

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests"
    - omv list -V
    - if [[ ${OMV_ENGINE} == "NON_OMV_TESTS" ]]; then echo "Continuing with tests not under OMV..."; else exit $OMV_SUCCESS; fi
    - echo "Running non OMV tests..."
    - python setup.py install

    
    # Testing c302

    - python c302/c302_IClamp.py A    
    - omv install NEURON # Need to install NEURON
    - omv list -V
    - export NEURON_HOME=/home/travis/neuron/nrn/x86_64/
    - python c302/runAndPlot.py -test
    - python c302/c302_utils.py -nogui

